security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\JWTAuthenticator

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\JWTAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /client-dashboard 
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: app_logout
                target: /login

    access_control:
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: CLIENT }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
